<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Lease;

class LeaseSeeder extends Seeder
{
    public function run(): void
    {
        for ($i = 1; $i <= 23; $i++) {

            Lease::create([

                'organization_id' => 1,

                'tenant_id' => $i,

                'unit_id' => $i,

                'start_date' => now()->subMonths(rand(1,24)),

                'end_date' => null,

                'rent_amount' => rand(18000,65000),

                'deposit_amount' => rand(18000,65000),

                'payment_frequency' => 'Monthly',

                'status' => 'Active',

                'notes' => 'Lease generated by seeder',

            ]);

        }
    }
}